id = "deepwiki-mcp"
name = "DeepWiki MCP Server"
description = "Zed extension for DeepWiki's Model Context Protocol server (Rust)"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <contact@example.com>"]
repository = "https://github.com/your/your-mcp-client"

[context_servers.deepwiki-mcp]
name = "DeepWiki MCP Server"
# To add more configuration/custom settings in Zed, add a [context_servers.deepwiki-mcp.settings] table here.
