# Cargo-deny configuration for deepwiki-mcp-server extension
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    "wasm32-wasip1", # Primary target for Zed extensions
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
# The path where the advisory databases are cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = [
    # Add specific advisories to ignore here if needed after review
    #"RUSTSEC-0000-0000",
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
]
# The confidence threshold for detecting a license from license text
confidence-threshold = 0.8
# Allow specific licenses for individual crates
exceptions = [
    # Serde ecosystem
    { allow = ["MIT", "Apache-2.0"], crate = "serde" },
    { allow = ["MIT", "Apache-2.0"], crate = "serde_json" },
    { allow = ["MIT", "Apache-2.0"], crate = "serde_derive" },
    # JSON schema library
    { allow = ["MIT"], crate = "schemars" },
]

[licenses.private]
ignore = false
registries = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "deny"
# The graph highlighting used when creating dotgraphs for crates with multiple versions
highlight = "all"
# Default features configuration
workspace-default-features = "allow"
external-default-features = "allow"

# List of crates to deny
deny = [
    # Insecure cryptographic libraries
    { crate = "openssl", reason = "Use rustls instead for better security" },
    { crate = "native-tls", reason = "Use rustls instead for better security" },
    # Unmaintained or problematic crates
    { crate = "chrono", reason = "Use time crate for new code" },
]

# Certain crates/versions that will be skipped when doing duplicate detection
skip = []

skip-tree = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in the allow list
unknown-git = "warn"
# List of URLs for allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
