# Release configuration for deepwiki-mcp-server Zed extension
# Configured for WASM-based Zed extension releases

# Enable semantic versioning and changelog management
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}" },
    { file = "extension.toml", search = "version = \".*\"", replace = "version = \"{{version}}\"" },
    { file = "Cargo.toml", search = "version = \".*\"", replace = "version = \"{{version}}\"" },
]

# Configure git operations for extension repository
allow-branch = ["main", "master"]
sign-commit = false
sign-tag = false
push-remote = "origin"

# Configure publishing - extensions are distributed through Zed registry
publish = false

# Configure tagging for extension releases
tag-message = "Release deepwiki-mcp-server extension {{version}}"
tag-prefix = "extension-v"

# Pre-release hooks for WASM extension quality assurance
pre-release-hook = [
    "cargo fmt --check",
    "cargo clippy --target wasm32-wasip1 -- -D warnings",
    "cargo nextest run",
    "cargo build --target wasm32-wasip1 --release",
]

# Dependencies update configuration
dependent-version = "upgrade"

# Extension-specific configuration
consolidate-commits = false
